# 無効にするルール
disabled_rules:
- trailing_whitespace # 余分に改行がある方が視認性が上がる為、無効
- type_name # クラス名は長くして情報を詰めておく必要もある為、無効
- vertical_parameter_alignment # アノテーションを使うだけで警告が出てしまうため、無効
- multiple_closures_with_trailing_closure # SwiftUIの記述をしていると避けられない箇所が多いため、無効（Buttonの作成時など）
- identifier_name # Identifieableに準拠しようとすると`id`プロパティを宣言するため、無効
- nesting # 2段階のネストを記述したいケースがちょこちょこ発生したので、無効

# ルール一覧を表示
#- colon
#- control_statement
#- file_length
#- force_cast
#- function_body_length
#- leading_whitespace
#- line_length
#- nesting
#- operator_whitespace
#- return_arrow_whitespace
#- todo
#- trailing_newline
#- variable_name_max_length
#- variable_name_min_length
#- type_body_length
#- variable_name

# 一行の文字列制限を100文字から300文字に変更
line_length: 300

excluded: # Lint対象から外すファイルのあるパスを記述
- Pods
- R.generated.swift
- Apollo
- vendor
- CoineyKit

# クラスの行数
type_body_length:
- 200 # warning
- 400 # error

# 変数名の最大文字数
variable_name_max_length:
- 60 # warning
- 80 # error

# 変数名の最小文字数
variable_name_min_length:
- 1 # warning
- 0 # error

# 関数の長さ
function_body_length:
- 100 # warning
- 200 # error

# タプルの大きさ
large_tuple:
- 3
